### ISSUE TITLE
Dataset Renovation - APM_DAILY

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/salurbal-fair-renovations#13]
https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/APM_DAILY/v1.0

## Action Items 
  - [x] ETL setup
  - [x] define data-metadata relationships -> **linkage.csv**
  - [x] generate codebook templates -> **4.0-template__codebooks.xlsx**
  - [x] initial filling out of codebooks  -> **4.1-raw__codebooks.xlsx**
  - [ ] QC of initial codebooks -> **4.2-base__codebooks.xlsx**
  - [ ] Review of base codebooks  -> **4.3-int__codebooks.xlsx**
  - [ ] QC of intermediate codebooks  -> **4.4-final__codebooks.xlsx**
  - [ ] Integration and loading into data warehouse

**Comment by ran-codes** [comment]
note hold off on setting up any daily monthly data.

Will do these in next refactor (where we add geo levels to datawarehouse).

**Comment by ran-codes** [comment]
setup for APM_DAILY and APM_MONTHLY done together. so deleting the APM_MONTH issue.

**Comment by ran-codes** [comment]
@dianahiguera setup is done and ready for you to start renovating.

- repo: https://github.com/Drexel-UHC/salurbal-fair-renovations/tree/main/datasets/APM_DAILY/v1.0
- server: \\files.drexel.edu\colleges\SOPH\Shared\UHC\Projects\Wellcome_Trust\Data Methods Core\Data\Air_Pollution

**Comment by dianahiguera** [comment]
@ran-codes @juruchi Linkage done :)

**Comment by juruchi** [comment]
@dianahiguera template codebook generated

**Comment by dianahiguera** [comment]
@ran-codes raw__codebook ready for review. 
I modified the linkage and added a tab for sources that vary by country. (by_dataset_by_iso). Additionally, I included sources for SV and PA that were not in the dataset. 
I can look over whether that tab was correctly filled if you generate a new template for the codebook with the new linkage. Please let me know.

**Comment by ran-codes** [comment]
Good call @dianahiguera !! it looks good to me.

One minor piece of feedback: when you have some columns that are don't have any values just leave them empty instead of using `NA`.

Thanks again ! 🍰

**Comment by ran-codes** [comment]
@kam642  The codebook is ready for your review. Details on codebook fields can be found [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx) Let us know if you have any questions!

## Action items


- [ ] Review [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12303404/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by kam642** [comment]
@ran-codes @juruchi The sources for this data differs by city in some of the countries. Should I add a column for SALID1 in teh by_dataset_iso2 worksheet?

**Comment by ran-codes** [comment]
Good question. @kam642 is it for many cities or just a few?

**Comment by kam642** [comment]
@ran-codes There are a total of 102 cities.
AR=1 - one source
BR=20 - from 4 different sources depending on which monitor system
CL=18 - one source for whole country
CO = 21 - one source for whole country
MX=38 - one source for whole country
PA=1 - one source
PE=2 - Both cities have a different source
SV=1 - one source

**Comment by ran-codes** [comment]
@kam642  The codebook is ready for your review. Details on codebook fields can be found [here](https://github.com/Drexel-UHC/salurbal-fair-renovations/raw/main/documents/templates/_template_details.xlsx) Let us know if you have any questions!


**Please utilize both sheets both sheets (`by_dataset_iso2` and `by_dataset_iso2_salid1`) on a case by case basis to fill in source.  Please leave any unused cells blank. e.g. for MX the source cells in `by_dataset_iso2_salid1` should be blank because this is already filled in `by_dataset_iso2`. Let us know if you have any questions. **

## Action items

- [ ] Review [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12741275/4.2-base__codebook.xlsx)
- [ ] Make edits as needed and save in a file called **4.3-int__codebook.xlsx**
- [ ] Comment in this issue when the final version is ready and upload the file to this issue via drag and drop

**Comment by kam642** [comment]
Query about sources sent to Nelson:
I’m getting the information together for the SALURBAL data portal for the air pollution daily monitor data and have some questions about the data use terms for some of the sources.

For Colombia: I have that the data is downloaded from http://aircolombia.sisaire.gov.co/portal/MainPage.col but I’m not able to access this site to review the terms of use. Are you able to access this?

For Brazil Estado de São Paulo: When I go to the website https://cetesb.sp.gov.br/ar/qualar/ it looks like it requires a log in. What are the terms of use for the data once it’s downloaded after logging in? Are there any restrictions or do you agree to any terms when you obtain log in credentials?

For Brazil Estado do Rio de Janeiro: A website was not provided in the documentation for this source. Can you provide this? Data downloaded from Instituto Estadual do Ambiente - INEA-RJ (Estado do Rio de Janeiro)

For Brazil Estado de Minas Gerais: : I have that the data is downloaded from http://www.feam.br/qualidade-do-ar/dados but I’m not able to access this site to review the terms of use. Are you able to access this?

For Mexico: The data requested by SALURBAL partner to Instituto Nacional de Ecologia y Cambio Climatico – INECC, Secretaria de Medio Ambiente y Recusos Naturaltes, Gobierno de México, not a direct download. What are the terms of use for obtaining this data?

For Panama: The data requested by SALURBAL partner to Instituto Especializado de Análisis da Universidad de Panamá, not a direct download. What are the terms of use for obtaining this data?

For Peru Lima: The Data requested by SALURBAL partner to Servicio Nacional de Meteorologia e Hidrologia del Perú – SENAMHI, not a direct download. What are the terms of use for obtaining this data?



Note: I was able to find the information I need for Argentina, Chile, Brazil Espírito Santo, and Peru Arequipa. All are no restrictions.

**Comment by kam642** [comment]
Response from Claudio:
See below some information for each location:

- Colombia: I think the following link is working: [http://sisaire.ideam.gov.co/ideam-sisaire-web/informacion.xhtml?de=que_es](https://nam10.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsisaire.ideam.gov.co%2Fideam-sisaire-web%2Finformacion.xhtml%3Fde%3Dque_es&data=05%7C01%7Ckam642%40drexel.edu%7Ccd8bc826d32744430adf08dbc9c662f7%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C638325626137595610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mytWdIF8G6nCHG48FP3d3joAnYhLQxGE3pMCaO7DrkM%3D&reserved=0). At the bottom of the site, there are links to "Condiciones y términos de uso de la Información" and "Política de publicación de datos en la Web-Revisada y Ajustada" where I think you may find the information you need.

- Brasil (Sao Paulo): after the login, the data portal does not provide information on the data usage policy, there are only reports generator and data download tools. I did not find a specific document on data use policy on other CETESB's pages.
- Brazil (Rio de Janeiro): access has been updated to the following link: [https://portalsigqar.inea.rj.gov.br/](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fportalsigqar.inea.rj.gov.br%2F&data=05%7C01%7Ckam642%40drexel.edu%7Ccd8bc826d32744430adf08dbc9c662f7%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C638325626137595610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lez8cQiHbVbX8slCvYyp5ZAyDgorUZrb7fp7MIk8n%2Bc%3D&reserved=0). I also did not find a specific document about the data use policy.

- Brazil (Minas Gerais): the website appears to be momentarily down, so I can't find information too. 

The data from these three states were published on the [Air Quality Platform](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fenergiaeambiente.org.br%2Fqualidadedoar%2F&data=05%7C01%7Ckam642%40drexel.edu%7Ccd8bc826d32744430adf08dbc9c662f7%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C638325626137595610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6qwcUyhTbfUVYfBsARu%2B5RhhqzMt6DzpTFMxFYBtRC4%3D&reserved=0), a website launched by a Brazilian NGO. I'm just mentioning this platform because I think data from Brazil has been used without restrictions, but I'm not sure.

- Mexico, Panama, and Peru: for these countries, the data was requested by Salubal's colleagues, and no information about the data use was shared. For Mexico, José Texcalac transferred data that was already used in his other projects to Salurbal; For Panama, Kevin Martinez e-mailed to University of Panama requesting data for Salurbal; and for Peru, Akram Hernandez also requested data to SENAMHI for Salurbal.

**Comment by kam642** [comment]
Mexico response from Jose Luis Texcalac Sangrador jtexcalac@insp.mx
Air pollution data is public information and is available for download to the public through the official website of the National Institute of Ecology and Climate Change (INECC acronym in Spanish).
The link is https://sinaica.inecc.gob.mx/

Peru response from Akram Hernández Vásquez akram.hernandez.v@upch.pe
Regarding the information requested, these are obtained from the reports published by SENAMHI and therefore there are no restrictions or conditions of use.
here are the links.
[https://m.inei.gob.pe/biblioteca-virtual/boletines/estadisticas-ambientales/1/#lista](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fm.inei.gob.pe%2Fbiblioteca-virtual%2Fboletines%2Festadisticas-ambientales%2F1%2F%23lista&data=05%7C01%7Ckam642%40drexel.edu%7C70fad383752b4a7942fd08dbd49dd5c2%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C638337546596469783%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=u%2FkNa5CdoBaiw1Z%2FZdCxT%2FZtXlAdHSjrigVcMgeFD%2BY%3D&reserved=0)
[https://es.slideshare.net/ciimsa/monitoreo-de-aire-de-la-ciudad-de-arequipa-area-metropolitana-aos-2009-2011](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fes.slideshare.net%2Fciimsa%2Fmonitoreo-de-aire-de-la-ciudad-de-arequipa-area-metropolitana-aos-2009-2011&data=05%7C01%7Ckam642%40drexel.edu%7C70fad383752b4a7942fd08dbd49dd5c2%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C638337546596469783%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lP2F3qMSUdHF5TlfMk%2ByHRUserJ%2BCdII2HayXgpyRcM%3D&reserved=0)
[https://repositorio.senamhi.gob.pe/handle/20.500.12542/559](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Frepositorio.senamhi.gob.pe%2Fhandle%2F20.500.12542%2F559&data=05%7C01%7Ckam642%40drexel.edu%7C70fad383752b4a7942fd08dbd49dd5c2%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C638337546596469783%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zSqAeBrTwanRHj9EVZI707Ip%2FWhFiXHWwicRor%2Bwlpk%3D&reserved=0)

Panama response pending.

**Comment by kam642** [comment]
@ran-codes @juruchi 
Done. I'm still waiting for a response from Panama about DUA. I entered as 9 for public for now. Will send a note to update when I get a response.



[4.3-int__codebook.xlsx.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/13190800/4.3-int__codebook.xlsx.xlsx)

**Comment by juruchi** [comment]
@ran-codes The linkage and base codebook files on github for this dataset don't match the linkage screenshot and the base_codebook file link earlier in this conversation. Am I missing something?



> ## Developer notes
> @ran-codes @juruchi
> 
> Interesting edge-case. So in this case the linkage of source metadata varies based on country. Sometimes it's one source for a country but sometimes it's one source per city for a country. I think this is a typical pattern in some datasets and we should adopt it accordingly in our processing to account for this. One way to allow this flexibility is to enable linkages.csv to be able to have multiple values for a single metadata field conditioned that those linkages are hierarchical (e.g. `parent` `parent_suffix`)
> 
> ![image](https://user-images.githubusercontent.com/45013044/271021894-f1a2ae60-74d5-47ef-a559-1173753fcd91.png)
> 
> Then when templates are generated. `source` will be operationalized in both sheets. For renovators, this will mean they can utilize either to fill in source information. So for example in this case (as per the comment above) for SV, source would be filled in the 'by_dataset_iso2`, and then for PE source would be filled out in `by_dataset_iso2_salid1`.
> 
> Operatoinalization tracked in #176



> ## Action items
> * [x]  Review [4.2-base__codebook.xlsx](https://github.com/Drexel-UHC/salurbal-fair-renovations/files/12741275/4.2-base__codebook.xlsx)

**Comment by ran-codes** [comment]
@kam642 thank you for the update. 

@juruchi we had proposed pipeline changes #176 to implement to accommodate the 'hierarchical linkages` such as source for this data.  But we never made that update (I think we waiting for the update codebook that Kari provided above). Now that we have it we can start working on it. 

- Lmk if our original proposal makes semantically that makes sense. #176 
- Also if want to work on or I can take stab at it.

**Comment by ran-codes** [comment]
Updates:

- [x] update linkage.csv for hierarchical linkages for public, source and ack
- [x] add a complex linkage flag during linkage processing
- [ ] modify linkage function to export complex template
- [ ] harmonize complex template with KM int__codebook
- [ ] update codebook funcs to conditional test based on complex linkage flag
- [ ] add downstream denomralization test for complex linkage flag

**Comment by ran-codes** [comment]
final processing done. Thanks everyone!
